import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Relogio from "@/components/Relogio/Relogio";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = new Date();

  return (
    <html lang="pt">
      <body
        className="
          flex flex-col items-center
          gap-6
          px-4 py-6
          md:px-20 md:py-10
          min-h-screen
        "
      >
        {/* HEADER */}
        <header className="flex flex-col items-center gap-4">
          <h1 className="text-xl md:text-2xl font-bold">
            React & Next.js
          </h1>

          <nav
            className="
              flex flex-wrap justify-center
              gap-2 md:gap-4
              text-sm md:text-base
            "
          >
            <Link href="/">Intro</Link>
            <Link href="/sobre">Sobre</Link>
            <Link href="/tecnologias">Tecnologias</Link>
            <Link href="/caracteristicas">Características</Link>
            <Link href="/projetos">Projetos</Link>
            <Link href="/contador">Contador</Link>
            <Link href="/input">Input</Link>
            <Link href="/produtos">Loja</Link>
          </nav>
        </header>

        {/* MAIN */}
        <main
          className="
            bg-yellow-700
            w-full
            max-w-9xl
            p-4 md:p-6
            rounded-2xl
            min-h-[70vh]
          "
        >
          {children}
        </main>

        {/* FOOTER */}
        <footer className="flex flex-col items-center text-sm gap-1">
          <span>DIW {data.getFullYear()}</span>
          <Relogio />
        </footer>
      </body>
    </html>
  );
}
